# Generated by Django 3.0.3 on 2020-10-07 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notepad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=100, verbose_name='put a title')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('note_content', models.TextField(verbose_name='write down your important note')),
                ('note_image', models.ImageField(upload_to='note_image', verbose_name='Image')),
                ('saving_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
